# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Блог1
tagline:          'Из маркетинга в аналитику'
description:      'Пишу о попытках освоить Python и большие данные'
url:              https://drewleks.github.io/
baseurl:          "/about-me"

author:
  name:           
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Drewleks
